### ISSUE TITLE
When to have an online meeting and how often should it be?

### ISSUE THREAD

**Issue by tian3rd** [u6004244/miniGroup#5]
It is now really convenient to have a meeting using ZOOM. But everyone has a different course plan, so what is the best way to arrange this?

**Comment by yen311** [comment]
Maybe weekend?

**Comment by tian3rd** [comment]
> Maybe weekend? @tian3rd

That'll do. Maybe we can vote for the meeting time?
For example:
1. Saturday 12:00 - 3:00 pm
2. Saturday 3:00 - 6:00 pm
3. Saturday 6:00 - 9:00 pm
4. Saturday 9:00 - 11:59 pm
or 
5-8 the same timelines on Sunday accordingly. 
5. Sunday 12:00 - 3:00 pm, etc...

**Comment by yen311** [comment]
Sure! But where can we create the vote?

**Comment by tian3rd** [comment]
> Sure! But where can we create the vote?

Let's try this one:

/polls "Saturday 12:00 - 3:00 pm" "Saturday 3:00 - 6:00 pm" "Saturday 6:00 - 9:00 pm" "Saturday 9:00 - 11:59 pm" "Sunday 12:00 - 3:00 pm" "Sunday 3:00 - 6:00 pm" "Sunday 6:00 - 9:00 pm" "Sunday 9:00 - 11:5900 pm"

**Comment by yen311** [comment]
I preferred  "Saturday 12:00 - 3:00 pm", "Saturday 9:00 - 11:59 pm" && "Sunday 12:00 - 3:00 pm". But actually I'm free on most of the time.

**Comment by tian3rd** [comment]
> I preferred "Saturday 12:00 - 3:00 pm", "Saturday 9:00 - 11:59 pm" && "Sunday 12:00 - 3:00 pm". But actually I'm free on most of the time.

Haha, actually we can vote on this: refer to issue#9

**Comment by yen311** [comment]
I just saw it lol!

**Comment by tian3rd** [comment]
We have a poll to gather opinions, so this is a good time to close this issue.
