### ISSUE TITLE
Assignment 2 Skeleton discussion 

### ISSUE THREAD

**Issue by u6004244** [u6004244/miniGroup#7]

**Comment by tian3rd** [comment]
"what you need to submit is outline/skeleton of what you plan to build. This means deciding on what **classes** you think you’ll need and what **fields and methods** you will most likely want. You then need to create those classes, fields and methods, and give them some **documentation**." Quote from deliverables.

**Comment by tian3rd** [comment]
It is due this morning so now is a good time to close this issue.
